site_name: My Stories
site_url: https://avezshariq.github.io/my-stories/
theme:
  name: dracula
  logo: assets/styles/favicon.svg
  favicon: assets/styles/favicon.svg

use_directory_urls: true

nav:
  - "Portfolio Home ğŸ§”ğŸ»â€â™‚ï¸": ../../index.html
  - "Blog Home ğŸ“–": index.md
  - Projects: ../../projects.html
  - About: ../../about.html

extra_css:
  - assets/styles/extra.css
